# This is a basic workflow to help you get started with Actions

name: MAKEPKG

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: ls
        run: ls && pwd
        
      - name: Arch makepkg
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          # Path to DIRECTORY where the PKGBUILD file is. Assumes the directory is the name of package, ie /path/to/pkgname/
          pkgname: .
          # Validation target. Can be one of: "pkgbuild", "srcinfo", "run"
          target: pkgbuild # default is pkgbuild
          # Command to run after package installation. Used when target=run
          command: ls # optional
          # Turns debugging on
          debug: true # optional
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls
